import { upsertMany as upsertCategories } from './categories'
import { upsertMany as upsertProducts } from './products'
import type { Product, ProductCategory } from '../types'

const SEED_KEY = 'pos_seeded_v2'

export const CATEGORIES: ProductCategory[] = [
  { id: 'cat-adhesives',   name: 'Adhesives & Sealants' },
  { id: 'cat-taps',        name: 'Taps & Faucets' },
  { id: 'cat-pipes',       name: 'Pipes & Fittings' },
  { id: 'cat-valves',      name: 'Valves' },
  { id: 'cat-bathroom',    name: 'Bathroom Accessories' },
  { id: 'cat-locks',       name: 'Locks & Security' },
  { id: 'cat-tools',       name: 'Tools & Equipment' },
  { id: 'cat-abrasives',   name: 'Abrasives & Cutting Discs' },
  { id: 'cat-fasteners',   name: 'Clips & Fasteners' },
]

export const PRODUCTS: Product[] = [
  // ── Adhesives & Sealants ────────────────────────────────────────────────
  { id: 'p-adh-001', name: 'Tangit 250ml',                    sku: 'TNG-250',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-002', name: 'Tangit 500ml',                    sku: 'TNG-500',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-003', name: 'Silicon Henkel Clear',             sku: 'SIL-HNK',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-004', name: 'Silicon Sheng Bao',                sku: 'SIL-SHB',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-005', name: 'Tizo',                             sku: 'TIZ-001',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-006', name: 'Era 500ml',                        sku: 'ERA-500',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-007', name: 'DLG 243ml',                        sku: 'DLG-243',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-008', name: 'DLG Silicon',                      sku: 'DLG-SIL',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-009', name: 'Potoc Black',                      sku: 'POT-BLK',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-010', name: 'Potoc White',                      sku: 'POT-WHT',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-011', name: 'Potoc Clear',                      sku: 'POT-CLR',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-012', name: 'PPR Cement 1/2"',                  sku: 'PPR-CEM',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-013', name: 'PVC Bond 4"',                      sku: 'PVC-BND',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-014', name: 'Red Glue (pump)',                   sku: 'RED-GLU',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-015', name: 'Arldite',                          sku: 'ARL-001',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-016', name: 'Ardalite',                         sku: 'ARD-001',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-017', name: 'Aquafix Wall',                     sku: 'AQF-WAL',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-018', name: 'Magnifier Pillar',                 sku: 'MAG-PIL',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-019', name: 'PVC Glue 1/2L',                    sku: 'PVC-GLU',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-020', name: 'Boss White 400g',                  sku: 'BWH-400',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-021', name: 'Boss White 1/4kg',                 sku: 'BWH-250',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },
  { id: 'p-adh-022', name: 'Super Douch Foam',                 sku: 'SDF-001',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-adhesives' },

  // ── Taps & Faucets ──────────────────────────────────────────────────────
  { id: 'p-tap-001', name: 'KK Basin Tap',                     sku: 'KKB-TAP',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },
  { id: 'p-tap-002', name: 'Pillar Tap Linko',                  sku: 'PIL-LNK',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },
  { id: 'p-tap-003', name: 'Wall Tap Linko',                    sku: 'WAL-LNK',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },
  { id: 'p-tap-004', name: 'Pillar Self Closing',               sku: 'PIL-SLC',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },
  { id: 'p-tap-005', name: 'Kingmisa Mixer',                    sku: 'KNG-MIX',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },
  { id: 'p-tap-006', name: 'Uzuri Kitchen Tap',                 sku: 'UZU-KIT',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },
  { id: 'p-tap-007', name: 'PPR Tap 1/2"',                      sku: 'PPR-TAP',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },
  { id: 'p-tap-008', name: 'BPF Tap',                           sku: 'BPF-TAP',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },
  { id: 'p-tap-009', name: 'Garden Tap 3/4"',                   sku: 'GDN-34T',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },
  { id: 'p-tap-010', name: 'Garden Tap 1/2"',                   sku: 'GDN-12T',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },
  { id: 'p-tap-011', name: 'PPR Handle Bar 3/4"',               sku: 'PPR-H34',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },
  { id: 'p-tap-012', name: 'PPR Handle Bar 1/2"',               sku: 'PPR-H12',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },
  { id: 'p-tap-013', name: 'Basin Mixers',                      sku: 'BAS-MIX',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },
  { id: 'p-tap-014', name: 'Wash Tap (Chrome)',                  sku: 'WSH-CHR',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },
  { id: 'p-tap-015', name: 'Pillar Tap (Plastic)',               sku: 'PIL-PLS',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },
  { id: 'p-tap-016', name: 'Pillar Tap (Waste)',                 sku: 'PIL-WST',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-taps' },

  // ── Pipes & Fittings ────────────────────────────────────────────────────
  { id: 'p-pip-001', name: 'MTD Bush 4x3',                      sku: 'MTD-43B',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-002', name: 'MTD Bush 4x2',                      sku: 'MTD-42B',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-003', name: 'MTD Bush',                           sku: 'MTD-BSH',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-004', name: 'Plug 3"',                            sku: 'PLG-3IN',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-005', name: '1 Way',                              sku: 'FIT-1WY',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-006', name: '4" 45° Bend',                        sku: 'BND-445',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-007', name: '4 Way',                              sku: 'FIT-4WY',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-008', name: 'MTD Sec 3/4"',                       sku: 'MTD-S34',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-009', name: 'Tee 2" PVC',                         sku: 'TEE-2VC',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-010', name: 'Bend 2" 90°',                        sku: 'BND-290',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-011', name: 'Bend 3"',                            sku: 'BND-3IN',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-012', name: 'Tee 3"',                             sku: 'TEE-3IN',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-013', name: 'Tank Connector 1/2"',                sku: 'TNK-C12',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-014', name: 'Tank Connector 3/4"',                sku: 'TNK-C34',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-015', name: 'Tank Connector 1"',                  sku: 'TNK-C1I',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-016', name: 'Tank Connector 1 1/2"',              sku: 'TNK-C15',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-017', name: 'Tank Connector 2"',                  sku: 'TNK-C2I',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-018', name: 'Conn Strip',                         sku: 'CON-STR',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-019', name: 'Tail Off',                           sku: 'TAI-OFF',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-020', name: 'End Cap',                            sku: 'END-CAP',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-021', name: 'PPR Union 32mm',                     sku: 'PPR-U32',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-022', name: 'PPR Union 20mm',                     sku: 'PPR-U20',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-023', name: 'PVC H/D Coupling 32mm',              sku: 'PVC-C32',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-024', name: 'Tee 3/4" PPR',                       sku: 'TEE-34P',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-025', name: 'Elbow 1/2" PPR',                     sku: 'ELB-12P',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-026', name: 'Socket 1/2" PPR',                    sku: 'SCK-12P',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-027', name: 'PPR Socket 3/4"',                    sku: 'PPR-S34',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-028', name: 'Socket 1" PPR',                      sku: 'SCK-1IP',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-029', name: 'Elbow 1" PPR',                       sku: 'ELB-1IP',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-030', name: 'PVC Socket 1" PPR',                  sku: 'PVC-S1P',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-031', name: 'Adapting Socket 3/4" x 1/2"',        sku: 'ADP-SCK',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-032', name: 'Reducing Socket 32x25mm',            sku: 'RED-S32',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-033', name: 'Reducing PVC 2" - 1 1/2"',           sku: 'RED-PVC',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-034', name: 'MTD MI 50mm',                        sku: 'MTD-M50',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-035', name: 'MTD MI 40mm',                        sku: 'MTD-M40',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-036', name: 'Dubi Sinks 1" PPR',                  sku: 'DUB-SNK',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-037', name: 'Knit MTD 1/2"',                      sku: 'KNT-M12',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-038', name: 'Nipple 1/2"',                        sku: 'NIP-12I',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-039', name: 'Super Union (Plastic)',               sku: 'SUP-UNI',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-040', name: 'Shoshana',                           sku: 'SHO-001',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-041', name: 'H/Down 20mm',                        sku: 'HDN-20M',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-042', name: 'Dop Caps',                           sku: 'DOP-CAP',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-043', name: 'PPR Pipe 1/2" 50m',                  sku: 'PPR-50M',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-044', name: 'PPR Pipe 1/2" 15m',                  sku: 'PPR-15M',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-045', name: 'PPR Pipe 1/2" 30m',                  sku: 'PPR-30M',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-046', name: 'PPR Pipe Gift 1/2"',                  sku: 'PPR-GFT',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-047', name: 'Shower Pipe 1 1/2"',                  sku: 'SHW-P15',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-048', name: 'Shower Pipe 1"',                      sku: 'SHW-P1I',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-049', name: 'Shower Pipe 1/2" 4ft',               sku: 'SHW-P4F',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-050', name: 'Shower Pipe 1/2" 3ft',               sku: 'SHW-P3F',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },
  { id: 'p-pip-051', name: 'Shower Pipe 3/4"',                    sku: 'SHW-P34',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-pipes' },

  // ── Valves ──────────────────────────────────────────────────────────────
  { id: 'p-val-001', name: 'Min Valve',                          sku: 'MIN-VAL',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },
  { id: 'p-val-002', name: 'High Level Ball Valve',              sku: 'HLB-VAL',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },
  { id: 'p-val-003', name: 'Magic Valve 1/2" White',             sku: 'MAG-V12',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },
  { id: 'p-val-004', name: 'Magic Valve 1 1/4" White',           sku: 'MAG-V14',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },
  { id: 'p-val-005', name: 'Magic Valve 1 1/2" Chrome',          sku: 'MAG-V15',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },
  { id: 'p-val-006', name: 'Gate Valve 1/2"',                    sku: 'GAT-V12',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },
  { id: 'p-val-007', name: 'Ang Valve Henmed',                   sku: 'ANG-HMD',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },
  { id: 'p-val-008', name: 'Neat Valve 12mm',                    sku: 'NET-V12',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },
  { id: 'p-val-009', name: 'Neat Valve 10mm',                    sku: 'NET-V10',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },
  { id: 'p-val-010', name: 'Neat Valve 8mm',                     sku: 'NET-V08',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },
  { id: 'p-val-011', name: 'Neat Valve 6mm',                     sku: 'NET-V06',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },
  { id: 'p-val-012', name: 'Float Valve',                        sku: 'FLT-VAL',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },
  { id: 'p-val-013', name: 'Automatic Control Valve',            sku: 'AUT-CTL',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },
  { id: 'p-val-014', name: 'Bullcock 3/4" PVC',                  sku: 'BUL-V34',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },
  { id: 'p-val-015', name: 'Bullcock 1/2" PVC',                  sku: 'BUL-V12',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },
  { id: 'p-val-016', name: 'Hanks',                              sku: 'HNK-VAL',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-valves' },

  // ── Bathroom Accessories ────────────────────────────────────────────────
  { id: 'p-bat-001', name: 'Ena Shower',                         sku: 'ENA-SHW',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-002', name: 'Shower Rose',                        sku: 'SHW-RSE',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-003', name: 'Arabic Toilet',                      sku: 'ARB-TOI',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-004', name: 'Bathroom Shelf Uzuri',               sku: 'BTH-SHF',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-005', name: 'Soap Dish',                          sku: 'SOP-DSH',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-006', name: 'Soap Holder',                        sku: 'SOP-HLD',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-007', name: 'Liquid Soap Holder Wall Mount',      sku: 'LQD-SOP',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-008', name: 'Tissue Holder (Plastic)',             sku: 'TIS-PLS',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-009', name: 'Tissue Holder (Chrome)',              sku: 'TIS-CHR',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-010', name: 'Tissue Holder (Gold)',                sku: 'TIS-GLD',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-011', name: 'Toothbrush Holder (Plastic)',         sku: 'TTH-HLD',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-012', name: 'Drying Rack (Dish)',                  sku: 'DRY-RCK',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-013', name: 'Bottle Trap (Plastic)',               sku: 'BTL-TPL',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-014', name: 'Bottle Trap S/S 1 1/4"',             sku: 'BTL-T14',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-015', name: 'Bottle Trap S/S 1 1/2"',             sku: 'BTL-T15',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-016', name: 'Urinal Waste',                       sku: 'URI-WST',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },
  { id: 'p-bat-017', name: 'Suction Top Flush',                  sku: 'SUC-FLS',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-bathroom' },

  // ── Locks & Security ────────────────────────────────────────────────────
  { id: 'p-lck-001', name: 'Lock (Golden)',                      sku: 'LCK-GLD',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-locks' },
  { id: 'p-lck-002', name: 'Lock (Silver)',                      sku: 'LCK-SLV',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-locks' },
  { id: 'p-lck-003', name: 'Door Lock',                          sku: 'LCK-DOR',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-locks' },

  // ── Tools & Equipment ───────────────────────────────────────────────────
  { id: 'p-tol-001', name: 'Pipe Cutter (Small)',                sku: 'PPC-SML',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-002', name: 'Screwdriver (Lucas)',                sku: 'SDR-LCS',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-003', name: 'Screwdriver (Big)',                  sku: 'SDR-BIG',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-004', name: 'Self Screwdriver',                   sku: 'SDR-SLF',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-005', name: '2-in-1 Screwdriver',                sku: 'SDR-2N1',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-006', name: 'Solar Welding Goggles',              sku: 'SOL-GOG',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-007', name: 'Hacksaw',                            sku: 'HCK-SAW',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-008', name: 'Chalk Line',                         sku: 'CHK-LNE',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-009', name: 'Spirit Level',                       sku: 'SPR-LVL',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-010', name: 'Pliers',                             sku: 'PLR-001',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-011', name: 'Trowel',                             sku: 'TRW-001',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-012', name: 'Trowel 7"',                          sku: 'TRW-7IN',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-013', name: 'Chuck Key',                          sku: 'CHK-KEY',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-014', name: 'Drill Bits Set',                     sku: 'DRL-SET',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-015', name: 'Drill Bits',                         sku: 'DRL-BIT',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-016', name: 'Drill Bits 18mm',                    sku: 'DRL-18M',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-017', name: 'Flat Bits',                          sku: 'FLT-BIT',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-018', name: 'Jigsaw Blades',                      sku: 'JIG-BLD',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-019', name: 'Glass Cutter',                       sku: 'GLS-CUT',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-020', name: 'Shovel (Flat)',                      sku: 'SHV-FLT',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-021', name: 'Allen Key 2"',                       sku: 'ALN-KEY',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-022', name: 'Chisel',                             sku: 'CSL-001',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-023', name: 'Pipe Wrench 18"',                    sku: 'PWR-18I',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-024', name: 'Shackle',                            sku: 'SHK-001',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-025', name: 'Drill',                              sku: 'DRL-001',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-026', name: 'Hand Saw 18"',                       sku: 'HSW-18I',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-027', name: 'Hand Saw 16"',                       sku: 'HSW-16I',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-028', name: 'Shears',                             sku: 'SHR-001',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-029', name: 'Solder Wire',                        sku: 'SOL-WIR',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-030', name: 'Electrode',                          sku: 'ELC-001',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-031', name: 'Maders (Rubber Mallet)',             sku: 'MAD-RBR',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-032', name: 'Aloe Brush',                         sku: 'ALO-BRS',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-033', name: 'Corona Brush',                       sku: 'COR-BRS',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },
  { id: 'p-tol-034', name: 'End Clothing',                       sku: 'END-CLT',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-tools' },

  // ── Abrasives & Cutting Discs ───────────────────────────────────────────
  { id: 'p-abr-001', name: 'Grinding Disc 7"',                   sku: 'GRD-7IN',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-abrasives' },
  { id: 'p-abr-002', name: 'Poly Disc',                          sku: 'PLY-DSC',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-abrasives' },
  { id: 'p-abr-003', name: 'Diamond Cutting Disc',               sku: 'DMD-DSC',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-abrasives' },
  { id: 'p-abr-004', name: 'Cutting Disc Wood 7" Cali',          sku: 'CUT-W7C',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-abrasives' },
  { id: 'p-abr-005', name: 'Cutting Disc 9" Castiel',            sku: 'CUT-9CS',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-abrasives' },
  { id: 'p-abr-006', name: 'Cutting Disc Rhodius S.L',           sku: 'CUT-RHD',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-abrasives' },
  { id: 'p-abr-007', name: 'Cutting Disc 9" S.L',                sku: 'CUT-9SL',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-abrasives' },
  { id: 'p-abr-008', name: 'Cutting Disc (Iron)',                 sku: 'CUT-IRN',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-abrasives' },

  // ── Clips & Fasteners ───────────────────────────────────────────────────
  { id: 'p-fas-001', name: 'Insulating Tape (Small)',             sku: 'INS-TAP',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-fasteners' },
  { id: 'p-fas-002', name: 'Guft Clip',                          sku: 'GFT-CLP',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-fasteners' },
  { id: 'p-fas-003', name: 'MTD Clip 1/2"',                      sku: 'MTD-C12',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-fasteners' },
  { id: 'p-fas-004', name: 'Metal Clip 1/2"',                    sku: 'MET-C12',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-fasteners' },
  { id: 'p-fas-005', name: 'Binding Wire 20"',                   sku: 'BND-WIR',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-fasteners' },
  { id: 'p-fas-006', name: 'Thread Seal (Large)',                 sku: 'THD-LRG',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-fasteners' },
  { id: 'p-fas-007', name: 'Thread Seal (Small)',                 sku: 'THD-SML',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-fasteners' },
  { id: 'p-fas-008', name: 'Gypsum Screws',                      sku: 'GYP-SCR',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-fasteners' },
  { id: 'p-fas-009', name: 'Screws 1"',                          sku: 'SCR-1IN',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-fasteners' },
  { id: 'p-fas-010', name: 'Steel Nails 2"',                     sku: 'STL-NAL',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-fasteners' },
  { id: 'p-fas-011', name: 'Self-Tapping Screws',                sku: 'SLF-SCR',  sellingPrice: 0, costPrice: 0, categoryId: 'cat-fasteners' },
]

export async function seedIfEmpty(): Promise<void> {
  if (typeof window === 'undefined') return
  if (localStorage.getItem(SEED_KEY)) return
  await upsertCategories(CATEGORIES)
  await upsertProducts(PRODUCTS)
  localStorage.setItem(SEED_KEY, '1')
}
